Repository rohan472000/Java-DSA-InterviewPrep, pull requests merged in 2023-10, with the labels that each got.

#31 Added Documentation and Code files
  .github/workflows/PR_template.md
  Graphs/README.md
  LL/README.md
  Queue/README.md
  Search/README.md
  Search/linear_Search.java
  Stack/README.md
  Threads/README.md
  Trees/README.md
Labels: hacktoberfest, hactoberfest-accepted

#33 Added README.md to BST directory
  BST/README.md
Labels: hactoberfest-accepted

#32 SieveofEratosthenes.java
  MathsforDSA/SieveofEratosthenes.java
Labels: hacktoberfest

#40 Update pull_request_template.md
  .github/pull_request_template.md
Labels: hacktoberfest

#41 Update pull_request_template.md
  .github/pull_request_template.md
Labels: hacktoberfest

#42 Update pull_request_template.md
  .github/pull_request_template.md
Labels: hacktoberfest-accepted

#43 Delete abc.py
  abc.py
Labels: hacktoberfest-accepted

#45 Update README.md
  LL/README.md
Labels: hacktoberfest-accepted

#52 Added all string question in one folder
  String/Min_window_substring.java
  String/addStrings.java
  String/fibonacci.java
  String/first_last_occurence_string.java
  String/integerToEnglishword.java
  String/longestubtrings.java
  String/remove_adjacent_duplicates.java
  String/rev_string.java
  String/validParenthesis.java
  String/x_at_end_ofString.java
Labels: hacktoberfest-accepted

#50 shell sort
  sorting/shell_sort.java
Labels: hactoberfest-accepted

#59 Added Circular LL
  LL/circular_LL.java
Labels: hacktoberfest-accepted

#62 Update README with directory structure information.
  README.md
Labels: hacktoberfest-accepted

#61 Added/topological sorting
  Graphs/topological_sorting.java
Labels: hacktoberfest-accepted

#69 Disjoint_Set_Union.java
  Graphs/DisjointSetUnion.java
Labels: hacktoberfest-accepted

#70 added segment_tree in tree
  Trees/segment_tree
Labels: hacktoberfest-accepted

#72 Adding a Setter/Getter generator
  Reflection-API/README.md
  Reflection-API/SetterGetterGenerator.java
  Reflection-API/TestCase.java
  Reflection-API/tmp.data
Labels: hacktoberfest-accepted

#74 Delete PR.md
  PR.md
Labels: hacktoberfest-accepted

#75 Added doubly circular LL
  LL/doubly_circular_LL.java
Labels: hacktoberfest-accepted

#83 TOC redirecting to the particular Topics
  README.md
Labels: hacktoberfest-accepted

#84 Update README.md
  README.md
Labels: hacktoberfest-accepted

#86 Added/fibonacci-factorial-with test cases
  MathsforDSA/factorial.java
  MathsforDSA/fibonacci.java
  factorial.java
Labels: hacktoberfest-accepted

#88 moved the files to the respective repository
  Graphs/dijkstra.java
  Leetcode/Kadane_algo.java
  Leetcode/Tiles_placement.java
  Leetcode/TrappingWater.java
  Leetcode/stock2_buySell.java
  Leetcode/stock_buySell.java
  MathsforDSA/permutation_II.java
  MathsforDSA/x_n_power.java
  String/stringbuilder.java
Labels: hacktoberfest-accepted

#89 resources closed
  Reflection-API/SetterGetterGenerator.java
Labels: hacktoberfest-accepted

#90 Implemented graph using ArrayList in java
  .github/pull_request_template.md
  Graphs/GraphUsingArrayList.java
Labels: hacktoberfest-accepted

#76 Added Sudoku.java file
  Backtracking/Sudoku.java
Labels: hacktoberfest-accepted

#91 Fixed File Structure
  Array/bitManipulation.java
  Graphs/maxPath_inMaze.java
  MathsforDSA/isSquareFul.java
  sorting/recursion1.java
Labels: hacktoberfest-accepted
